env:
  node: true
  es6: true
extends:
  - 'eslint-config/config/canonical'
  - 'eslint-config/config/import'
  - 'eslint-config/config/javascript'
  - 'eslint-config/config/react'
  - 'eslint-config/config/typescript'
  - 'eslint-config/config/vitest'

  - 'plugin:json/recommended-with-comments'
parserOptions:
  tsconfigRootDir: __dirname
