env:
  node: true
  es6: true
extends:
  - 'eslint-configs/canonical'
  - 'eslint-configs/import'
  - 'eslint-configs/javascript'
  - 'eslint-configs/jest'
  - 'eslint-configs/react'
  - 'eslint-configs/typescript'

  - 'plugin:json/recommended-with-comments'
